### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by JadeDever** [Goxiaoy/go-saas-kit#17]
when I use "docker-compose -f docker-compose.yml -f docker-compose.tracing.yml up -d" my device is Mac m1 chip

**Comment by Goxiaoy** [comment]
probably fixed by adding override file `docker-compose.arm.yml`
```yaml
services:
  mysqld:
    platform: linux/amd64
```
`docker-compose -f docker-compose.yml -f docker-compose.tracing.yml -f docker-compose.arm.ym up -d`
